"""Public API for the Jacobian counterexample factory."""

from .factory import (
    A_TARGET,
    B_TARGET,
    C,
    C_TARGET,
    R,
    T,
    VARS,
    CollisionCertificate,
    FrameCertificate,
    VerificationReport,
    collision_certificate,
    counterexample_map,
    evaluate,
    exact_jacobian_determinant,
    fiber_polynomial,
    frame_certificate,
    generate_n,
    rational_frame_map,
    reconstruct_source_from_root,
    verify,
    x,
    y,
    z,
)

__all__ = [
    "A_TARGET",
    "B_TARGET",
    "C",
    "C_TARGET",
    "R",
    "T",
    "VARS",
    "CollisionCertificate",
    "FrameCertificate",
    "VerificationReport",
    "collision_certificate",
    "counterexample_map",
    "evaluate",
    "exact_jacobian_determinant",
    "fiber_polynomial",
    "frame_certificate",
    "generate_n",
    "rational_frame_map",
    "reconstruct_source_from_root",
    "verify",
    "x",
    "y",
    "z",
]
