import "./math.js";

const math = globalThis.JacobianMath;

export const {
  analyzeAutomorphismFiber,
  analyzeCounterexampleFiber,
  automorphismFiberCoefficients,
  automorphismJacobian,
  automorphismOffset,
  boundaryChartSource,
  cAbs,
  cAdd,
  cDiv,
  cMul,
  cPow,
  cScale,
  cSub,
  collisionCertificate,
  complex,
  derivativeCoefficients,
  deriveAsinhAxisTransform,
  deriveFiberDisplayTransform,
  deriveLandscapeDisplayTransform,
  determinant3,
  detectMultipleRoots,
  evaluateAutomorphismMap,
  evaluateCounterexampleMap,
  evaluatePolynomial,
  fiberPolynomialCoefficients,
  formatComplex,
  formatNumber,
  frameCurvePoint,
  framePolynomialCoefficients,
  invertAutomorphismMap,
  isFiniteComplex,
  polynomialEvaluationScale,
  realCriticalTargets,
  reconstructSource,
  relativePolynomialResidual,
  solvePolynomial,
  threeRealPreset,
  trimPolynomial,
  verifyCollisionNumerically,
} = math;
