(function installJacobianTourContent(root) {
"use strict";

root.JacobianTourContent = Object.freeze([
  {
    id: "welcome",
    chapter: "Welcome",
    title: "A local rule with a global surprise",
    anchor: ".viewport",
    scene: "welcome",
    body: "The full map lives in C³—six real dimensions—so it cannot be drawn directly. Pip will guide you through a one-variable fiber that exposes the whole mystery.",
    detail: "The glowing geometry is a numerical view of exact formulas. The tour will always distinguish a picture from a proof certificate.",
  },
  {
    id: "question",
    chapter: "1 · The conjecture",
    title: "Can a perfect local inverse force one global inverse?",
    anchor: "#classification",
    scene: "automorphism-identity",
    body: "A polynomial map F sends an input point to an output point. Its Jacobian determinant measures the map’s first-order change near each input.",
    formula: "det DF = constant ≠ 0  ?⇒  F has a polynomial inverse",
    detail: "The Jacobian conjecture predicted “yes.” The counterexamples make the implication fail in complex dimension three.",
  },
  {
    id: "local",
    chapter: "2 · The local guarantee",
    title: "A nonzero Jacobian protects every tiny neighborhood",
    anchor: "#jacobian-metric",
    scene: "automorphism-identity",
    body: "When det DF never vanishes, the inverse function theorem gives a local inverse near every finite point.",
    detail: "Plain English: sufficiently nearby inputs remain distinguishable. The map does not locally collapse a complex direction.",
    quiz: {
      question: "Does that local inverse automatically give one global inverse?",
      choices: [
        ["Yes, local always becomes global", false, "That was the hoped-for leap—but local neighborhoods can still overlap globally."],
        ["Not necessarily", true, "Exactly. The discovery separates local invertibility from global one-to-one behavior."],
      ],
    },
  },
  {
    id: "control",
    chapter: "3 · A control case",
    title: "This is the conjecture-compatible world",
    anchor: ".family-switch",
    scene: "automorphism-chain",
    body: "Triangular shears are nonlinear polynomial maps, but they have an explicit polynomial inverse. Every target has exactly one source.",
    formula: "(x,y,z) ↦ (x + yᵏ, y + zᵏ, z)",
    detail: "Watch the interface report Jacobian 1 and one finite affine preimage.",
  },
  {
    id: "counterexample",
    chapter: "4 · The break",
    title: "Keep the local guarantee. Break the global conclusion.",
    anchor: "[data-family='counterexample']",
    scene: "cubic-collision",
    body: "The cubic counterexample has det DG₃ = −2 everywhere, yet distinct inputs share an output. There is no global inverse.",
    formula: "det DG₃ = −2,   but   G₃(p₁) = G₃(p₂) = G₃(p₃)",
    detail: "Nothing singular happens at any finite source point. The failure is genuinely global.",
  },
  {
    id: "collision",
    chapter: "5 · Exact collision",
    title: "One target has three finite preimages",
    anchor: ".accounting",
    scene: "cubic-collision",
    body: "At the output (−¼, 0, 0), three distinct source points land together. The accounting panel tracks all three without inventing a critical point.",
    formula: "(0,0,−¼), (1,−3/2,13/2), (−1,3/2,13/2)  ↦  (−¼,0,0)",
    detail: "The stored collision and constant determinant are exact symbolic certificates; the browser only replays them numerically.",
    tryLabel: "Show the next source",
    try: "cycle-source",
  },
  {
    id: "fiber",
    chapter: "6 · The visual seam",
    title: "Six real dimensions reduce to one polynomial equation",
    anchor: ".equation-panel",
    scene: "cubic-collision",
    body: "Fix an output (α,β,γ). On the chart x ≠ 0, each simple root T of the fiber polynomial reconstructs one source point.",
    formula: "P(T) = h_d(T,γ) + βT − 2α = 0,      x = 2 / P′(T)",
    detail: "This reduction is why a high-dimensional polynomial map can become visual. In the family G_d, a generic target has d sheets: cubic, quartic, and quintic members carry 3, 4, and 5 roots.",
  },
  {
    id: "boundary",
    chapter: "7 · A second chart",
    title: "The third source is finite—not “at infinity”",
    anchor: ".inspector",
    scene: "boundary-source",
    body: "The coordinate T uses 1/x, so a source with x = 0 lies outside the T-chart. The lab reconstructs it separately in a second affine chart.",
    detail: "At the cubic collision, the inspector now highlights the finite source (0, 0, −¼). A missing chart coordinate is not the same thing as a missing point.",
  },
  {
    id: "escape",
    chapter: "8 · Escape through infinity",
    title: "Sheets run away instead of folding at a finite point",
    anchor: "#escape-metric",
    scene: "cubic-tangency",
    body: "At a repeated fiber root, P and P′ vanish together. Then x = 2/P′ cannot remain finite, so the associated sheets escape the affine picture.",
    formula: "P(T) = 0 and P′(T) = 0   ⇒   |x| → ∞",
    detail: "This is the key mechanism: the finite map stays locally invertible while global behavior is controlled by what happens near infinity.",
  },
  {
    id: "complex",
    chapter: "9 · The complex view",
    title: "Real slices are only part of the story",
    anchor: ".mode-switch",
    scene: "complex-landscape",
    body: "The map lives over complex numbers. The landscape plots log(1 + |P(T)|); each numerical zero appears as a well, including non-real roots.",
    detail: "The residual reports how accurately the browser located a root. Exact identities and numerical rendering remain visibly separate.",
  },
  {
    id: "remarkable",
    chapter: "10 · Why it matters",
    title: "The discovery splits two ideas once expected to coincide",
    anchor: "#truth-strip",
    scene: "cubic-collision",
    body: "The examples are locally invertible everywhere and still globally overlap. They show that a constant nonzero Jacobian does not force a polynomial map to be globally invertible.",
    detail: "That is remarkable because the obstruction is not a finite singularity, numerical accident, or hidden fold: it is exact algebra plus global behavior at infinity.",
  },
  {
    id: "explore",
    chapter: "Your turn",
    title: "Ask the lab three questions",
    anchor: ".preset-grid",
    scene: "cubic-collision",
    body: "Exact collision: how can several finite sources share one target? Nearby fiber: how do the sheets move? Escape wall: what changes when P and P′ share a root?",
    detail: "You now have the four-part picture: local inverse, fiber roots, global overlap, and escape through infinity. Finish here and the lab will leave you at the exact cubic collision.",
    tryLabel: "Replay the exact collision",
    try: "cubic-collision",
  },
]);
})(globalThis);
